// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.8.2
// - protoc             v3.19.4
// source: blug/v1/blug.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationBlugCreateNewFriendLink = "/blug.v1.Blug/CreateNewFriendLink"

type BlugHTTPServer interface {
	// CreateNewFriendLink Friend service
	CreateNewFriendLink(context.Context, *CreateNewFriendLinkReq) (*CreateNewFriendLinkResp, error)
}

func RegisterBlugHTTPServer(s *http.Server, srv BlugHTTPServer) {
	r := s.Route("/")
	r.POST("/api/friends/add", _Blug_CreateNewFriendLink0_HTTP_Handler(srv))
}

func _Blug_CreateNewFriendLink0_HTTP_Handler(srv BlugHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateNewFriendLinkReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBlugCreateNewFriendLink)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateNewFriendLink(ctx, req.(*CreateNewFriendLinkReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateNewFriendLinkResp)
		return ctx.Result(200, reply)
	}
}

type BlugHTTPClient interface {
	CreateNewFriendLink(ctx context.Context, req *CreateNewFriendLinkReq, opts ...http.CallOption) (rsp *CreateNewFriendLinkResp, err error)
}

type BlugHTTPClientImpl struct {
	cc *http.Client
}

func NewBlugHTTPClient(client *http.Client) BlugHTTPClient {
	return &BlugHTTPClientImpl{client}
}

func (c *BlugHTTPClientImpl) CreateNewFriendLink(ctx context.Context, in *CreateNewFriendLinkReq, opts ...http.CallOption) (*CreateNewFriendLinkResp, error) {
	var out CreateNewFriendLinkResp
	pattern := "/api/friends/add"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationBlugCreateNewFriendLink))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
