// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.20.3
// source: blug/v1/blug.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateNewFriendLinkReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title  string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Link   string `protobuf:"bytes,2,opt,name=link,proto3" json:"link,omitempty"`
	Desc   string `protobuf:"bytes,3,opt,name=desc,proto3" json:"desc,omitempty"`
	Avatar string `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
}

func (x *CreateNewFriendLinkReq) Reset() {
	*x = CreateNewFriendLinkReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blug_v1_blug_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateNewFriendLinkReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNewFriendLinkReq) ProtoMessage() {}

func (x *CreateNewFriendLinkReq) ProtoReflect() protoreflect.Message {
	mi := &file_blug_v1_blug_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNewFriendLinkReq.ProtoReflect.Descriptor instead.
func (*CreateNewFriendLinkReq) Descriptor() ([]byte, []int) {
	return file_blug_v1_blug_proto_rawDescGZIP(), []int{0}
}

func (x *CreateNewFriendLinkReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateNewFriendLinkReq) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *CreateNewFriendLinkReq) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *CreateNewFriendLinkReq) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

type CreateNewFriendLinkResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string  `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Check   *Result `protobuf:"bytes,2,opt,name=check,proto3" json:"check,omitempty"`
}

func (x *CreateNewFriendLinkResp) Reset() {
	*x = CreateNewFriendLinkResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blug_v1_blug_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateNewFriendLinkResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNewFriendLinkResp) ProtoMessage() {}

func (x *CreateNewFriendLinkResp) ProtoReflect() protoreflect.Message {
	mi := &file_blug_v1_blug_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNewFriendLinkResp.ProtoReflect.Descriptor instead.
func (*CreateNewFriendLinkResp) Descriptor() ([]byte, []int) {
	return file_blug_v1_blug_proto_rawDescGZIP(), []int{1}
}

func (x *CreateNewFriendLinkResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateNewFriendLinkResp) GetCheck() *Result {
	if x != nil {
		return x.Check
	}
	return nil
}

type Result struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Msg    string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *Result) Reset() {
	*x = Result{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blug_v1_blug_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_blug_v1_blug_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_blug_v1_blug_proto_rawDescGZIP(), []int{2}
}

func (x *Result) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Result) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_blug_v1_blug_proto protoreflect.FileDescriptor

var file_blug_v1_blug_proto_rawDesc = []byte{
	0x0a, 0x12, 0x62, 0x6c, 0x75, 0x67, 0x2f, 0x76, 0x31, 0x2f, 0x62, 0x6c, 0x75, 0x67, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x62, 0x6c, 0x75, 0x67, 0x2e, 0x76, 0x31, 0x1a, 0x1c, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x6e, 0x0a, 0x16, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x4e, 0x65, 0x77, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x4c, 0x69,
	0x6e, 0x6b, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6c,
	0x69, 0x6e, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6c, 0x69, 0x6e, 0x6b, 0x12,
	0x12, 0x0a, 0x04, 0x64, 0x65, 0x73, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64,
	0x65, 0x73, 0x63, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x22, 0x5a, 0x0a, 0x17, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x4e, 0x65, 0x77, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x4c, 0x69,
	0x6e, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x25, 0x0a, 0x05, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0f, 0x2e, 0x62, 0x6c, 0x75, 0x67, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x52, 0x05, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x22, 0x32, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x32, 0x7f, 0x0a, 0x06, 0x46,
	0x72, 0x69, 0x65, 0x6e, 0x64, 0x12, 0x75, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4e,
	0x65, 0x77, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x4c, 0x69, 0x6e, 0x6b, 0x12, 0x1f, 0x2e, 0x62,
	0x6c, 0x75, 0x67, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4e, 0x65, 0x77,
	0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x4c, 0x69, 0x6e, 0x6b, 0x52, 0x65, 0x71, 0x1a, 0x20, 0x2e,
	0x62, 0x6c, 0x75, 0x67, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4e, 0x65,
	0x77, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x4c, 0x69, 0x6e, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x22,
	0x1b, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x15, 0x3a, 0x01, 0x2a, 0x22, 0x10, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x73, 0x2f, 0x61, 0x64, 0x64, 0x32, 0x09, 0x0a, 0x07,
	0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x42, 0x15, 0x5a, 0x13, 0x62, 0x6c, 0x75, 0x67, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x62, 0x6c, 0x75, 0x67, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_blug_v1_blug_proto_rawDescOnce sync.Once
	file_blug_v1_blug_proto_rawDescData = file_blug_v1_blug_proto_rawDesc
)

func file_blug_v1_blug_proto_rawDescGZIP() []byte {
	file_blug_v1_blug_proto_rawDescOnce.Do(func() {
		file_blug_v1_blug_proto_rawDescData = protoimpl.X.CompressGZIP(file_blug_v1_blug_proto_rawDescData)
	})
	return file_blug_v1_blug_proto_rawDescData
}

var file_blug_v1_blug_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_blug_v1_blug_proto_goTypes = []interface{}{
	(*CreateNewFriendLinkReq)(nil),  // 0: blug.v1.CreateNewFriendLinkReq
	(*CreateNewFriendLinkResp)(nil), // 1: blug.v1.CreateNewFriendLinkResp
	(*Result)(nil),                  // 2: blug.v1.Result
}
var file_blug_v1_blug_proto_depIdxs = []int32{
	2, // 0: blug.v1.CreateNewFriendLinkResp.check:type_name -> blug.v1.Result
	0, // 1: blug.v1.Friend.CreateNewFriendLink:input_type -> blug.v1.CreateNewFriendLinkReq
	1, // 2: blug.v1.Friend.CreateNewFriendLink:output_type -> blug.v1.CreateNewFriendLinkResp
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_blug_v1_blug_proto_init() }
func file_blug_v1_blug_proto_init() {
	if File_blug_v1_blug_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_blug_v1_blug_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateNewFriendLinkReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blug_v1_blug_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateNewFriendLinkResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blug_v1_blug_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Result); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_blug_v1_blug_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_blug_v1_blug_proto_goTypes,
		DependencyIndexes: file_blug_v1_blug_proto_depIdxs,
		MessageInfos:      file_blug_v1_blug_proto_msgTypes,
	}.Build()
	File_blug_v1_blug_proto = out.File
	file_blug_v1_blug_proto_rawDesc = nil
	file_blug_v1_blug_proto_goTypes = nil
	file_blug_v1_blug_proto_depIdxs = nil
}
