// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.8.2
// - protoc             v3.20.3
// source: blug/v1/blug.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationFriendCreateNewFriendLink = "/blug.v1.Friend/CreateNewFriendLink"

type FriendHTTPServer interface {
	CreateNewFriendLink(context.Context, *CreateNewFriendLinkReq) (*CreateNewFriendLinkResp, error)
}

func RegisterFriendHTTPServer(s *http.Server, srv FriendHTTPServer) {
	r := s.Route("/")
	r.POST("/api/friends/add", _Friend_CreateNewFriendLink0_HTTP_Handler(srv))
}

func _Friend_CreateNewFriendLink0_HTTP_Handler(srv FriendHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateNewFriendLinkReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationFriendCreateNewFriendLink)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateNewFriendLink(ctx, req.(*CreateNewFriendLinkReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateNewFriendLinkResp)
		return ctx.Result(200, reply)
	}
}

type FriendHTTPClient interface {
	CreateNewFriendLink(ctx context.Context, req *CreateNewFriendLinkReq, opts ...http.CallOption) (rsp *CreateNewFriendLinkResp, err error)
}

type FriendHTTPClientImpl struct {
	cc *http.Client
}

func NewFriendHTTPClient(client *http.Client) FriendHTTPClient {
	return &FriendHTTPClientImpl{client}
}

func (c *FriendHTTPClientImpl) CreateNewFriendLink(ctx context.Context, in *CreateNewFriendLinkReq, opts ...http.CallOption) (*CreateNewFriendLinkResp, error) {
	var out CreateNewFriendLinkResp
	pattern := "/api/friends/add"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationFriendCreateNewFriendLink))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
