// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.8.2
// - protoc             v3.20.3
// source: blug/v1/ping.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationPingTestSayPing = "/blug.v1.PingTest/SayPing"

type PingTestHTTPServer interface {
	SayPing(context.Context, *PingReq) (*PingResp, error)
}

func RegisterPingTestHTTPServer(s *http.Server, srv PingTestHTTPServer) {
	r := s.Route("/")
	r.GET("/ping/{name}", _PingTest_SayPing0_HTTP_Handler(srv))
}

func _PingTest_SayPing0_HTTP_Handler(srv PingTestHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in PingReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPingTestSayPing)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SayPing(ctx, req.(*PingReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PingResp)
		return ctx.Result(200, reply)
	}
}

type PingTestHTTPClient interface {
	SayPing(ctx context.Context, req *PingReq, opts ...http.CallOption) (rsp *PingResp, err error)
}

type PingTestHTTPClientImpl struct {
	cc *http.Client
}

func NewPingTestHTTPClient(client *http.Client) PingTestHTTPClient {
	return &PingTestHTTPClientImpl{client}
}

func (c *PingTestHTTPClientImpl) SayPing(ctx context.Context, in *PingReq, opts ...http.CallOption) (*PingResp, error) {
	var out PingResp
	pattern := "/ping/{name}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationPingTestSayPing))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
