// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.20.3
// source: blug/v1/ping.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	PingTest_SayPing_FullMethodName = "/blug.v1.PingTest/SayPing"
)

// PingTestClient is the client API for PingTest service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PingTestClient interface {
	SayPing(ctx context.Context, in *PingReq, opts ...grpc.CallOption) (*PingResp, error)
}

type pingTestClient struct {
	cc grpc.ClientConnInterface
}

func NewPingTestClient(cc grpc.ClientConnInterface) PingTestClient {
	return &pingTestClient{cc}
}

func (c *pingTestClient) SayPing(ctx context.Context, in *PingReq, opts ...grpc.CallOption) (*PingResp, error) {
	out := new(PingResp)
	err := c.cc.Invoke(ctx, PingTest_SayPing_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PingTestServer is the server API for PingTest service.
// All implementations must embed UnimplementedPingTestServer
// for forward compatibility
type PingTestServer interface {
	SayPing(context.Context, *PingReq) (*PingResp, error)
	mustEmbedUnimplementedPingTestServer()
}

// UnimplementedPingTestServer must be embedded to have forward compatible implementations.
type UnimplementedPingTestServer struct {
}

func (UnimplementedPingTestServer) SayPing(context.Context, *PingReq) (*PingResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayPing not implemented")
}
func (UnimplementedPingTestServer) mustEmbedUnimplementedPingTestServer() {}

// UnsafePingTestServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PingTestServer will
// result in compilation errors.
type UnsafePingTestServer interface {
	mustEmbedUnimplementedPingTestServer()
}

func RegisterPingTestServer(s grpc.ServiceRegistrar, srv PingTestServer) {
	s.RegisterService(&PingTest_ServiceDesc, srv)
}

func _PingTest_SayPing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PingTestServer).SayPing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PingTest_SayPing_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PingTestServer).SayPing(ctx, req.(*PingReq))
	}
	return interceptor(ctx, in, info, handler)
}

// PingTest_ServiceDesc is the grpc.ServiceDesc for PingTest service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PingTest_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "blug.v1.PingTest",
	HandlerType: (*PingTestServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayPing",
			Handler:    _PingTest_SayPing_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "blug/v1/ping.proto",
}
