// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"blug/internal/biz"
	"blug/internal/conf"
	"blug/internal/data"
	"blug/internal/server"
	"blug/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	friendRepo := data.NewFriendRepo(dataData, logger)
	friendUsecase := biz.NewFriendUsecase(friendRepo, logger)
	friendService := service.NewFriendService(friendUsecase)
	grpcServer := server.NewGRPCServer(confServer, friendService, logger)
	httpServer := server.NewHTTPServer(confServer, friendService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
