server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  database:
    driver: postgres
    source: postgres://postgres:pass@localhost:5432/blug?sslmode=disable
  redis:
    addr: 127.0.0.1:6379
    password: "taosu"
    read_timeout: 0.2s
    write_timeout: 0.2s
